### PR TITLE
Include proxy properties, commented out by default

### PR DESCRIPTION
**Pull request by hackily**
My previous pull request was auto-closed by the bot.
Having commented-out proxy properties will save future developers a lot of time.

### CODE REVIEW

**Comment by turnerth** [comment]
we hadn't reviewed those actually.  Will take a look and will try to find this evil bot.

**Comment by hackily** [comment]
Here comes the bot again! :laughing:

**Comment by hackily** [comment]
I'm suggesting that the property file should include commented out lines for proxies. Those lines did not exist beforehand. A developer would need to spend time figuring out where exactly to put a proxy, precisely because they will be unable to communicate with the Predix UAA.

A developer who tries to debug locally may be aware that they need a proxy, but they won't know exactly how the application is pulling the proxyHost and proxyPort.

A developer can have the proxies set up in their system environment and even in Eclipse, but this service requires the developer to explicitly define the proxy to get past the UAA when developing locally.

In a normal non-proxied use-case, the added comments do not affect them - the proxyHost and proxyPort variables will remain null for them.

But in a use-case where the developer is behind a proxy server, working for some company, if the pull request is accepted, they will now easily see the fact that they need to input their proxy information when they are modifying their application.properties file, thus saving them time.

**Comment by katyatalluri** [comment]
Thank you for the feedback. We have included the proxy properties (commented out) in the property files.

**Pull request closed without merging**
